apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: monitoring-apm-server
  namespace: monitoring
spec:
  version: 8.15.3
  count: 1
  elasticsearchRef:
    name: monitoring
  kibanaRef:
    name: monitoring