apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  registries.conf: |
    registries:
    - name: Docker Hub
      api_url: https://registry-1.docker.io
      prefix: docker.io
      credentials: pullsecret:argocd/docker-io-credentials
      default: true
      defaultns: library
    - name: stefanmuraru
      api_url: https://registry.stefanmuraru.com
      prefix: registry.stefanmuraru.com
      credentials: pullsecret:argocd/registry-stefanmuraru-com-pullsecret
  log.level: trace
