apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-stefanmuraru-com-pullsecret
  namespace: argocd
spec:
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  refreshPolicy: OnChange
  target:
    name: registry-stefanmuraru-com-pullsecret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"registry.stefanmuraru.com":{"auth":"{{ printf "deployer:%s" .password | b64enc }}"}}}
  data:
    - secretKey: password
      remoteRef:
        key: registry.stefanmuraru.com/deployer
