apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hive-driver-config
  namespace: democratic-csi
spec:
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  refreshPolicy: OnChange
  target:
    name: hive-driver-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        driver-config-file.yaml: |
          driver: freenas-api-nfs
          instance_id:
          httpConnection:
            protocol: https
            host: "{{ .api_host }}"
            port: 443
            apiKey: "{{ .api_key }}"
            allowInsecure: true
            apiVersion: 2
          zfs:
            datasetParentName: zoom/compute/nfs-volumes
            detachedSnapshotsDatasetParentName: zoom/compute/nfs-snapshots
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetPermissionsMode: "0777"
            datasetPermissionsUser: 0
            datasetPermissionsGroup: 0
          nfs:
            shareStrategy: "setDatasetProperties"
            shareHost: "{{ .nfs_share_host }}"
            shareAlldirs: false
            shareAllowedHosts: []
            shareAllowedNetworks:
              - 10.0.0.0/8
              - 10.42.0.0/16
            shareMaprootUser: root
            shareMaprootGroup: root
            shareMapallUser: ""
            shareMapallGroup: ""
  data:
    - secretKey: api_key
      remoteRef:
        key: kubestore-csi/api_key
    - secretKey: api_host
      remoteRef:
        key: kubestore-csi/api_host
    - secretKey: nfs_share_host
      remoteRef:
        key: kubestore-csi/nfs_share_host
