---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password-sdk
spec:
  provider:
    onepasswordSDK:
      vault: Infrastructure
      auth:
        serviceAccountSecretRef:
          name: secretstore-1password-token-infrastructure
          key: token
          namespace: external-secrets