apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-credentials
  namespace: registry
spec:
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  refreshPolicy: OnChange
  target:
    name: registry-credentials
    creationPolicy: Owner
  data:
    - secretKey: htpasswd
      remoteRef:
        key: registry.stefanmuraru.com/htpasswd
