apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: registry
  name: registry-data
spec:
  storageClassName: zoom
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
