apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudquery-config
data:
  config: |
    kind: source
    spec:
      name: k8s
      path: cloudquery/k8s
      registry: cloudquery
      version: "v6.0.11"
      tables: ["*"]
      destinations: ["postgresql"]
      spec:
        contexts: 
    ---
    kind: destination
    spec:
      name: "postgresql"
      path: "cloudquery/postgresql"
      registry: "cloudquery"
      version: "v8.0.3"
      spec:
        connection_string: ${PG_CONNECTION_STR}