apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/murarustefaan/homeops.git'
    targetRevision: HEAD
    path: n8n
  project: infrastructure
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
