apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-credentials
  namespace: n8n
spec:
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  refreshPolicy: OnChange
  target:
    name: n8n-credentials
    creationPolicy: Owner
  data:
    - secretKey: encryption_key
      remoteRef:
        key: auto.stefanmuraru.com/encryption_key
    - secretKey: oidc_client_id
      remoteRef:
        key: auto.stefanmuraru.com/oidc_client_id
    - secretKey: oidc_client_secret
      remoteRef:
        key: auto.stefanmuraru.com/oidc_client_secret
