apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: n8n
  name: n8n-appdata
spec:
  storageClassName: zoom
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi