apiVersion: v1
kind: Secret
metadata:
  name: credentials
data: {}

---

apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"

  deployment:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: docker-io-credentials

          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_USER
                      name: credentials
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_PASSWORD
                      name: credentials

  ingress:
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: "stefanmuraru-com-issuer"

    spec:
      ingressClassName: private
      rules:
        - host: monitoring.stefanmuraru.com
          http:
            paths:
              - backend:
                  service:
                    name: monitoring-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
      tls:
        - hosts:
            - monitoring.stefanmuraru.com
          secretName: monitoring-stefanmuraru-com-tls