apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: monitoring
  labels:
    prometheus: monitoring
spec:
  replicas: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: prometheus
                operator: In
                values:
                  - monitoring
          topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 100m
      memory: 400Mi
    limits:
      cpu: 200m
      memory: 800Mi
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 10Gi
  retention: 60d
  retentionSize: 7GiB
  
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus: monitoring