apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/tags/v0.86.1/bundle.yaml