apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: citadel
spec:
  version: 8.11.1
  count: 1

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

  elasticsearchRef:
    name: citadel
  
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: citadel

spec:
  routes:
    - match: HostSNI(`citadel.stefanmuraru.com`)
      services:
        - name: citadel-kb-http
          port: 5601
  tls:
    passthrough: true