apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-credentials
  namespace: paperless
spec:
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  refreshPolicy: OnChange
  target:
    name: paperless-credentials
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: docs.stefanmuraru.com/secret_key
    - secretKey: admin_password
      remoteRef:
        key: docs.stefanmuraru.com/admin_password
    - secretKey: keydb_password
      remoteRef:
        key: docs.stefanmuraru.com/keydb_password
    - secretKey: oidc_client_id
      remoteRef:
        key: docs.stefanmuraru.com/oidc_client_id
    - secretKey: oidc_client_secret
      remoteRef:
        key: docs.stefanmuraru.com/oidc_client_secret
    - secretKey: oidc_providers_json
      remoteRef:
        key: docs.stefanmuraru.com/oidc_providers_json
