apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: paperless
  name: paperless-data
spec:
  storageClassName: hive
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: paperless
  name: paperless-media
spec:
  storageClassName: hive
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: paperless
  name: paperless-consume
spec:
  storageClassName: hive
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: paperless
  name: paperless-export
spec:
  storageClassName: hive
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: paperless-keydb
  name: paperless-keydb-data
spec:
  storageClassName: zoom
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
