apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-credentials
  namespace: nextcloud
spec:
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  refreshPolicy: OnChange
  target:
    name: nextcloud-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: cloud.stefanmuraru.com/admin_username
    - secretKey: password
      remoteRef:
        key: cloud.stefanmuraru.com/admin_password
    - secretKey: redis-password
      remoteRef:
        key: cloud.stefanmuraru.com/redis_password
