spec:
  template:
    spec:
      containers:
        - name: authentik
          env:
            - name: AUTHENTIK_DATA__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik.authentik-data.credentials.postgresql.acid.zalan.do
                  key: password
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: AUTHENTIK_SECRET_KEY
            - name: AUTHENTIK_REDIS__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: REDIS_PASSWORD
            - name: AUTHENTIK_EMAIL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: EMAIL_PASSWORD
                  optional: true