apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-core
spec:
  destination:
    namespace: authentik
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.goauthentik.io'
    targetRevision: 2025.8.1
    chart: authentik
    helm:
      valueFiles:
        - values.yaml
  project: infrastructure
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
