namespace: authentik

resources:
  - deploy.app.yaml
  - postgresql.yaml
  - secret.yaml

secretGenerator:
  - name: authentik-secret
    literals:
      - password=
      - postgres-password=
      - secret_key=
    type: Opaque