apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-sdk
    kind: SecretStore
  target:
    name: authentik-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: password
        version: latest
        property: password
    - secretKey: secret_key
      remoteRef:
        key: secret_key
        version: latest
        property: secret_key
  dataFrom:
    - extract:
        key: remote-key-in-the-provider