postgresql:
  enabled: false

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: ""
  master:
    persistence:
      enabled: true
      size: 2Gi
      storageClass: "zoom"
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 500m

authentik:
  secret_key: ""
  error_reporting:
    enabled: true
  postgresql:
    host: "authentik-postgresql"
    name: "authentik"
    user: "authentik"
  redis:
    host: "authentik-redis-master"
    password: ""

ingress:
  enabled: true
  ingressClassName: "public"
  annotations:
    cert-manager.io/cluster-issuer: stefanmuraru-com-issuer
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/hostname: auth.stefanmuraru.com
    external-dns.alpha.kubernetes.io/target: d473da53-e5a4-4535-b3f0-6e36d165b874.cfargotunnel.com
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: auth.stefanmuraru.com
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - secretName: authentik-tls
      hosts:
        - auth.stefanmuraru.com

server:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

worker:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

volumes:
  media:
    enabled: true
    size: 5Gi
    storageClass: "zoom"
  templates:
    enabled: true
    size: 1Gi
    storageClass: "zoom"