apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-node-exporter-prometheus-sd
  labels:
    app: network-node-exporter-prometheus-sd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-node-exporter-prometheus-sd
  template:
    metadata:
      labels:
        app: network-node-exporter-prometheus-sd
    spec:
      containers:
      - name: network-prometheus-sd
        image: ghcr.io/murarustefaan/prometheus-sd-ipnet:latest
        imagePullPolicy: Always
        env:
        - name: NETWORK
          value: 10.0.4.0/23
        - name: INTERVAL
          value: "15m"
        - name: PORT
          value: "9100"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

---

apiVersion: v1
kind: Service
metadata:
  name: network-node-exporter-prometheus-sd
  labels:
    app: network-node-exporter-prometheus-sd
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: network-node-exporter-prometheus-sd