---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  selector:
    matchLabels:
      stefanmuraru.com/service: cloudflared
  replicas: 2
  template:
    metadata:
      labels:
        stefanmuraru.com/service: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
#            - --config
#            - /etc/cloudflared/config/config.yaml
            - run
            - --token
            - $(CLOUDFLARE_TOKEN)
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: CLOUDFLARE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-credentials
                  key: credentials.json
          volumeMounts:
#            - name: config
#              mountPath: /etc/cloudflared/config
#              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
      volumes:
        - name: creds
          secret:
            secretName: cloudflared-credentials
            items:
              - key: credentials.json
                path: credentials.json
        # Create a config.yaml file from the ConfigMap below.
#        - name: config
#          configMap:
#            name: cloudflared
#            items:
#              - key: config.yaml
#                path: config.yaml
