apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
spec:
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.22.3
    chart: base
    helm:
      valueFiles:
        - values.yaml
  project: infrastructure
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
