apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
spec:
  destination:
    name: ''
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.20.2
    chart: base
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: infrastructure
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
