controller:
  ingressClassResource:
    name: private
    default: true
    controllerValue: "k8s.io/ingress-nginx-private"

  ingressClass: private
  resources:
    requests:
      cpu: 100m
      memory: 90Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetMemoryUtilizationPercentage:
  service:
    type: LoadBalancer

  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 15
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 15

revisionHistoryLimit: 3