apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-flipper-ci
  namespace: buildkite
spec:
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  refreshPolicy: OnChange
  target:
    name: github-app-flipper-ci
    creationPolicy: Owner
  data:
    - secretKey: APP_ID
      remoteRef:
        key: flipper-ci/app_id
    - secretKey: INSTALLATION_ID
      remoteRef:
        key: flipper-ci/installation_id
    - secretKey: PRIVATE_KEY
      remoteRef:
        key: flipper-ci/private_key
