apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-auth-registry-stefanmuraru-com
  namespace: buildkite
spec:
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  refreshPolicy: OnChange
  target:
    name: registry-auth-registry-stefanmuraru-com
    creationPolicy: Owner
  data:
    - secretKey: PASSWORD
      remoteRef:
        key: registry.stefanmuraru.com/builder
