apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: buildkite-agent-token
  namespace: buildkite
spec:
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  refreshPolicy: OnChange
  target:
    name: buildkite-agent-token
    creationPolicy: Owner
  data:
    - secretKey: BUILDKITE_AGENT_TOKEN
      remoteRef:
        key: buildkite.stefanmuraru.com/agent_token
