---
- name: Gather facts
  gather_facts: true
  hosts: all
  user: "{{ ansible_user }}"
  become: true
  become_method: sudo

  tasks: 
    - name: Print hostname and OS version
      debug:
        msg: "Hostname: {{ ansible_hostname }} | OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
