apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpoller
  labels:
    app.kubernetes.io/name: unpoller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: unpoller
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unpoller
    spec:
      containers:
        - name: unpoller
          image: ghcr.io/unpoller/unpoller:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: unpoller-config
          env:
            - name: UP_UNIFI_CONTROLLER_0_USER
              valueFrom:
                secretKeyRef:
                  name: unpoller-credentials
                  key: username
            - name: UP_UNIFI_CONTROLLER_0_PASS
              valueFrom:
                secretKeyRef:
                  name: unpoller-credentials
                  key: password
      restartPolicy: Always