apiVersion: v1
kind: Service
metadata:
  name: unpoller
  labels:
    app.kubernetes.io/name: unpoller
spec:
  ports:
    - name: http
      port: 9130
      targetPort: 9130
  selector:
      app.kubernetes.io/name: unpoller