apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-credentials
  namespace: actions
spec:
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  refreshPolicy: OnChange
  target:
    name: github-app-credentials
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: actions.stefanmuraru.com/github_app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: actions.stefanmuraru.com/github_app_installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: actions.stefanmuraru.com/github_app_private_key.pem
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: buildkit-registry-auth
  namespace: actions
spec:
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  refreshPolicy: OnChange
  target:
    name: buildkit-registry-auth
    creationPolicy: Owner
    template:
      data:
        config.json: |
          {"auths":{"registry.stefanmuraru.com":{"auth":"{{ printf "builder:%s" .password | b64enc }}"}}}
  data:
    - secretKey: password
      remoteRef:
        key: registry.stefanmuraru.com/builder
