namespace: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.19.1/cert-manager.yaml
  - cluster-issuer.yaml
  - external-secret.yaml
  - monitoring.yaml

patches:
  - path: enable-gateway-api-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
