resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.15.1/cert-manager.yaml
  - cluster-issuer.yaml
  - secret.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --enable-gateway-api
