csiDriver:
  name: "org.democratic-csi.iscsi"

storageClasses:
  - name: flash
    defaultClass: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4

    mountOptions: []
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
        node-db.node.session.auth.authmethod: CHAP
        node-db.node.session.auth.username: flipper
        node-db.node.session.auth.password: -password-
      node-publish-secret:
      controller-expand-secret:

driver:
  config:
    driver: freenas-iscsi
    instance_id:
    httpConnection:
      protocol: https
      host: 10.0.4.2
      port: 443
      apiKey: -api-key-
      allowInsecure: true
      apiVersion: 2
    sshConnection:
      host: 10.0.4.2
      port: 22
      username: root
      password: ""
      privateKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        -----END OPENSSH PRIVATE KEY-----
    zfs:
      datasetParentName: flash/k8s/volumes
      detachedSnapshotsDatasetParentName: flash/k8s/snapshots

    iscsi:
      targetPortal: "10.0.6.2:3260"
      namePrefix: csi-flipper-
      nameSuffix: ""

      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 4
          targetGroupAuthType: CHAP
          targetGroupAuthGroup: 1

      extentBlocksize: 512
      extentRpm: "SSD"
      extentAvailThreshold: 0